### ISSUE TITLE
Disc number slightly off?

### ISSUE THREAD

**Issue by Vatyrias** [skiadas/HealCalc3#105]
Healcalc is mostly 3.58% above my actual data with current gear, Penance being 6.7%, OffPenance being 4.97%.
Solace and Holy Fire are about 2% below what they are for me (haste on ticks included).
http://eu.battle.net/wow/de/character/anetheron/Vatyria/advanced
This can most likely be ignored for now I guess, since it does not change the comparison of spells much and there are more important tasks.

**Comment by skiadas** [comment]
Hm, @Vatyrias  is this still an issue? Or should we close it?

**Comment by skiadas** [comment]
@Vatyrias I guess I'll close it for now. Feel free to reopen it.
