### ISSUE TITLE
AoE caps

### ISSUE THREAD

**Issue by Vatyrias** [skiadas/HealCalc3#114]
Heals cap on 6 targets if not stated otherwise or is limited in some sort. This includes Halo, Divine Star, HW: Sanctuary, Healing Rain, Monk-Statue-Breath-Thingie, Jade Wind (Crane Kick), Chi Explosion,  Uplift and Prism. Cascade caps on 31, Mushroom on 3.
Right now Halo and DS do not cap.

**Comment by skiadas** [comment]
Closing. I went ahead with 6 targets.
