### ISSUE TITLE
Error in the wiki page

### ISSUE THREAD

**Issue by enklave** [skiadas/HealCalc3#124]
The following is from the wiki

>### Spirit

>782 base spirit.

>Spirit translates to combat regen. The formula for mana regen is:

>```
>MP5 = 3197 + 2.064 * Spirit
>```

However according to [this thread](http://blue.mmo-champion.com/topic/318876-warlords-of-draenor-theorycraft-discussion/), spirit is 0.412207024 mana per second or 2.06103512 mp5

Minor I know, but still.

**Comment by skiadas** [comment]
Should be fixed now.
